name: Azure Salt Lab

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Apply or Destroy?"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply or Destroy
        run: terraform ${{ github.event.inputs.action }} -auto-approve
        working-directory: ./terraform